class Entry {
  final String number;
  final String title;
  final int pageNo;

  Entry(this.number, this.title, this.pageNo);
}

List<Entry> entries = [
  Entry('1', 'Short title, extent and commencement', 4),
  Entry('2', 'Definitions and interpretation', 4),
  Entry('3', 'What are not inventions', 8),
  Entry('4', 'Inventions relating to atomic energy not patentable', 9),
  Entry(
      '5',
      'Inventions where only methods or processes of manufacture patentable',
      9),
  Entry('6', 'Persons entitled to apply for patents', 10),
  Entry('7', 'Form of application', 10),
  Entry('8', 'Information and undertaking regarding foreign applications', 11),
  Entry('9', 'Provisional and complete specifications', 11),
  Entry('10', 'Contents of specifications', 12),
  Entry('11', 'Priority dates of claims of a complete specification', 14),
  Entry('12', 'Examination of application', 17),
  Entry('13',
      'Search for anticipation by previous publication and by prior claim', 18),
  Entry('14', 'Consideration of the report of examiner by Controller', 19),
  Entry(
      '15',
      'Power of Controller to refuse or require amended applications, etc., in certain case',
      19),
  Entry(
      '16',
      'Power of Controller to make orders respecting division of application',
      19),
  Entry(
      '17',
      'Power of Controller to make orders respecting dating of application',
      20),
  Entry('18', 'Powers of Controller in cases of anticipation', 20),
  Entry('19', 'Powers of Controller in case of potential infringement', 21),
  Entry(
      '20',
      'Powers of Controller to make orders regarding substitution of applicants, etc',
      21),
  Entry('21', 'Time for putting application in order for grant', 22),
  Entry('22', 'Acceptance of complete specification', 23),
  Entry('23', 'Advertisement of acceptance of complete specification', 23),
  Entry('24', 'Effect of acceptance of complete specification', 24),
  Entry('25', 'Opposition to the patent', 25),
  Entry(
      '26',
      'In cases of "obtaining" Controller may treat the patent as the patent of opponent',
      28),
  Entry('27', 'Refusal to patent without opposition', 29),
  Entry('28', 'Mention of inventor as such in patent', 29),
  Entry('29', 'Anticipation by previous publication', 31),
  Entry('30', 'Anticipation by previous communication to Government', 32),
  Entry('31', 'Anticipation by public display, etc', 32),
  Entry('32', 'Anticipation by public working', 32),
  Entry(
      '33',
      'Anticipation by use and publication after provisional Specification',
      33),
  Entry(
      '34',
      'No anticipation if circumstances are only as described in sections 29, 30, 31 and 32',
      33),
  Entry(
      '35',
      'Secrecy directions relating to inventions relevant for defence purposes',
      34),
  Entry('36', 'Secrecy directions to be periodically reviewed', 34),
  Entry('37', 'Consequences of secrecy directions', 35),
  Entry('38', 'Revocation of secrecy directions and extension of time', 35),
  Entry(
      '39',
      'Residents not to apply for patents outside India without prior permission',
      36),
  Entry('40', 'Liability for contravention of section 35 or section 39', 36),
  Entry('41', 'Finality of orders of Controller and Central Government', 36),
  Entry('42', 'Savings respecting disclosure to Government', 37),
  Entry('43', 'Grant of patents', 38),
  Entry('44', 'Amendment of patent granted to deceased applicant', 38),
  Entry('45', 'Date of patent', 38),
  Entry('46', 'Form, extent and effect of patent', 39),
  Entry('47', 'Grant of patents to be subject to certain conditions', 39),
  Entry('48', 'Rights of patentees', 39),
  Entry(
      '49',
      'Patent rights not infringed when used on foreign vessels etc., temporarily or accidentallyin India',
      40),
  Entry('50', 'Rights of co-owners of patents', 40),
  Entry('51', 'Power of Controller to give directions to co-owners', 41),
  Entry(
      '52',
      'Grant of patent to true and first inventor where it has been obtained by another in fraud ofhim',
      42),
  Entry('53', 'Term of patent', 42),
  Entry('54', 'Patents of addition', 44),
  Entry('55', 'Term of patents of addition', 44),
  Entry('56', 'Validity of patents of addition', 45),
  Entry(
      '57',
      'Amendment of application and specification or any document relating thereto beforeController',
      46),
  Entry('58', 'Amendment of specification before Appellate Board or High Court',
      47),
  Entry(
      '59',
      'Supplementary provisions as to amendment of application or specification',
      47),
  Entry('60', 'Applications for restorations of lapsed patents', 49),
  Entry(
      '61',
      'Procedure for disposal of applications for restoration of lapsed patents',
      49),
  Entry('62', 'Rights of patentees of lapsed patents which have been restored',
      50),
  Entry('63', 'Surrender of patents', 51),
  Entry('64', 'Revocation of patents', 51),
  Entry(
      '65',
      'Revocation of patent or amendment of complete specification on directions fromGovernment in cases relating to atomic energy',
      53),
  Entry('66', 'Revocation of patent in public interest', 54),
  Entry('67', 'Register of patents and particulars to be entered therein', 55),
  Entry(
      '68',
      'Assignments, etc., not to be valid unless in writing and duly executed',
      56),
  Entry('69', 'Registration of assignments, transmissions, etc', 56),
  Entry('70', 'Power of registered grantee or proprietor to deal with patent',
      57),
  Entry('71', 'Rectification of register by Appellate Board', 57),
  Entry('72', 'Register to be open for inspection', 58),
  Entry('73', 'Controller and other officers', 59),
  Entry('74', 'Patent office and its branches', 59),
  Entry(
      '75',
      'Restriction on employees of patent office as to right or interest in patents',
      59),
  Entry('76', 'Officers and employees not to furnish information, etc', 60),
  Entry('77', 'Controller to have certain powers of a civil court', 61),
  Entry('78', 'Power of Controller to correct clerical errors etc', 61),
  Entry(
      '79',
      'Evidence how to be given and powers of Controller in respect thereof',
      62),
  Entry('80', 'Exercise of discretionary powers by Controller', 62),
  Entry(
      '81', 'Disposal by Controller of applications for extension of time', 63),
  Entry('82', 'Definition of "patented articles" and "patentee"', 64),
  Entry('83', 'General principles applicable to working of patented inventions',
      64),
  Entry('84', 'Compulsory licences', 65),
  Entry('85', 'Revocation of patents by the Controller for non-working', 67),
  Entry(
      '86',
      'Power of Controller to adjourn applications for compulsory licences, etc., in certaincases',
      67),
  Entry('87',
      'Procedure for dealing with applications under sections 84 and 85', 68),
  Entry('88', 'Powers of Controller in granting compulsory licences', 69),
  Entry('89', 'General purposes for granting compulsory licences', 69),
  Entry('90', 'Terms and conditions of compulsory licences', 70),
  Entry('91', 'Licensing of related patents', 71),
  Entry(
      '92',
      'Special provision for compulsory licences on notifications by Central Government',
      71),
  Entry('93',
      'Order for licence to operate as a deed between parties concerned', 73),
  Entry('94', 'Termination of compulsory licence', 73),
  Entry('95', '[Omitted by the Patents (Amendment) Act, 2002]', 73),
  Entry('96', '[Omitted by the Patents (Amendment) Act, 2002]', 73),
  Entry('97', '[Omitted by the Patents (Amendment) Act, 2002]', 73),
  Entry('98', '[Omitted by the Patents (Amendment) Act, 2002]', 73),
  Entry('99', 'Meaning of use of invention for purposes of Government', 74),
  Entry(
      '100',
      'Power of Central Government to use inventions for purposes of Government',
      74),
  Entry(
      '101',
      'Rights of third parties in respect of use of invention for purposes of Government',
      76),
  Entry('102',
      'Acquisition of inventions and patents by the Central Government', 77),
  Entry(
      '103',
      'Reference to High Court of disputes as to use for purposes of Government',
      77),
  Entry('104', 'Jurisdiction', 79),
  Entry('105', 'Power of court to make declaration as to non-infringement', 79),
  Entry(
      '106',
      'Power of court to grant relief in cases of groundless threats of infringementproceedings',
      80),
  Entry('107', 'Defences, etc., in suits for infringement', 81),
  Entry('108', 'Reliefs in suit for infringement', 81),
  Entry(
      '109',
      'Right of exclusive licensee to take proceedings against infringement',
      81),
  Entry(
      '110',
      'Right of licensee under section 84 to take proceedings against infringement',
      82),
  Entry(
      '111',
      'Restriction on power of court to grant damages or account of profits for infringement',
      82),
  Entry('112',
      'Restriction on power of court to grant injunction in certain cases', 83),
  Entry(
      '113',
      'Certificate of validity of specification and costs of subsequent suits for infringementthereof',
      83),
  Entry('114', 'Relief for infringement of partially valid specification', 83),
  Entry('115', 'Scientific advisers', 84),
  Entry('116', 'Appellate Board', 85),
  Entry('117', 'Staff of Appellate Board', 85),
  Entry('118',
      'Contravention of secrecy provisions relating to certain inventions', 88),
  Entry('119', 'Falsification of entries in register, etc', 88),
  Entry('120', 'Unauthorised claim of patent rights', 88),
  Entry('121', 'Wrongful use of words "patent office"', 89),
  Entry('122', 'Refusal or failure to supply information', 89),
  Entry('123', 'Practice by non-registered patent agents', 89),
  Entry('124', 'Offences by companies', 89),
  Entry('125', 'Register of patent agents', 91),
  Entry('126', 'Qualifications for registration as patent agents', 91),
  Entry('127', 'Rights of patent agents', 92),
  Entry(
      '128',
      'Subscription and verification of certain documents by patent agents',
      92),
  Entry('129', 'Restrictions on practice as patent agents', 92),
  Entry('130', 'Removal from register of patent agents and restoration', 93),
  Entry('131', 'Power of Controller to refuse to deal with certain agents', 93),
  Entry('132',
      'Savings in respect of other persons authorised to act as agents', 93),
  Entry('133', 'Convention countries', 94),
  Entry(
      '134', 'Notification as to countries not providing for reciprocity', 94),
  Entry('135', 'Convention applications', 94),
  Entry('136', 'Special provisions relating to convention application', 95),
  Entry('137', 'Multiple priorities', 96),
  Entry('138', 'Supplementary provisions as to convention applications', 96),
  Entry(
      '139', 'Other provisions of Act to apply to convention applications', 97),
  Entry('140', 'Avoidance of certain restrictive conditions', 98),
  Entry('141', 'Determination of certain contracts', 99),
  Entry('142', 'Fees', 99),
  Entry('143', 'Restrictions upon publication of specification', 100),
  Entry('144', 'Reports of examiners to be confidential', 100),
  Entry('145', 'Publication of official journal', 100),
  Entry(
      '146', 'Power of Controller to call for information from patentees', 100),
  Entry('147', 'Evidence of entries, documents, etc', 101),
  Entry('148', 'Declaration by infant, lunatic etc', 101),
  Entry('149', 'Service of notices, etc., by post', 101),
  Entry('150', 'Security for costs', 101),
  Entry('151', 'Transmission of orders of courts to Controller', 102),
  Entry(
      '152',
      'Transmission of copies of specifications, etc., and inspection thereof',
      102),
  Entry('153', 'Information relating to patents', 102),
  Entry('154', 'Loss or destruction of patents', 102),
  Entry('155', 'Reports of Controller to be placed before Parliament', 102),
  Entry('156', 'Patent to bind Government', 103),
  Entry('157', 'Right of Government to sell or use forfeited articles', 103),
  Entry('158', 'Power of High Courts to make rules', 103),
  Entry('159', 'Power of Central Government to make rules', 103),
  Entry('160', 'Rules to be placed before Parliament', 106),
  Entry(
      '161',
      'Special provisions with respect to certain applications deemed to have been refusedunder Act 2 of 1911',
      106),
  Entry(
      '162',
      'Repeal of Act 2 of 1911 in so far as it relates to patents and savings',
      106),
  Entry('163', 'Amendment of Act 43 of 1958', 106),
];
